version: '3.8'
services:
  vprodb:
    build:
       context: ./Docker-files/db
    image: mdasif74/aprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MSQL_ROOT_PASSWORD=vprodbpass
  
  vprcache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
       context: ./Docker-files/app
    image: mdasif74/aprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapp

  vproweb:
    build:
       context: ./Docker-files/web
    image: mdasif74/aprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
   vprodbdata: {}
   vproappdata: {}
