version: '3.8'
services:
  aprodb:
    build:
      context: ./Docker-files/db
    image: mdasif74/aprofiledb
    container_name: aprodb
    ports:
      - "3306:3306"
    volumes:
      - aprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aprodbpass
  
  aprcache01:
    image: memcached
    ports:
      - "11211:11211"
  
  apromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  aproapp:
    build:
       context: ./Docker-files/app
    image: mdasif74/aprofileapp
    container_name: aproapp
    ports:
      - "8080:8080"
    volumes:
      - aproappdata:/usr/local/tomcat/webapp

  aproweb:
    build:
       context: ./Docker-files/web
    image: mdasif74/aprofileweb
    container_name: aproweb
    ports:
      - "80:80"

volumes:
   aprodbdata: {}
   aproappdata: {}
